<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1"/>
        <PackageReference Include="WebSocketSharper" Version="1.0.42"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Core\Routing\Discovery\" />
      <Folder Include="Core\Routing\Pending\" />
      <Folder Include="Core\Routing\Server\" />
    </ItemGroup>

</Project>
