<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.72" />
        <PackageReference Include="EchoLib.Configuration" Version="1.0.2"/>
        <PackageReference Include="EchoLib.Core.Snowflake" Version="1.2.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="WebSocketSharper" Version="1.0.42"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EchoLib\EchoLib.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="secrets.ini">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
